from django.urls import path
from .views import (
    RouteListView, RouteDetailView, RouteCreateView, RouteUpdateView, RouteDeleteView, RouteQuickCreateView, RouteQuickUpdateView, RouteCollectionPointQuickCreateView, RouteCollectionPointQuickUpdateView, RouteCollectionPointQuickDeleteView, RouteMilkCollectionQuickDeleteView,
    CollectionPointListView, CollectionPointCreateView, CollectionPointUpdateView, CollectionPointQuickCreateView, CollectionPointQuickUpdateView, CollectionPointQuickDeleteView, CollectionPointDetailView, CollectionPointFeeUpdateView, CollectionPointFeeCellSaveView, CollectionPointFeeHistoryDeleteView, CollectionPointBankAccountsUpdateView, CollectionPointBankAccountDeleteView, CollectionPointBankAccountPrimaryView, CollectionPointBankAccountImportExcelView, CollectionPointBankAccountImportTemplateView, CollectionPointAdditionalFarmersView, CollectionPointStatementPrintView, CollectionPointPeriodReceiptView, FarmerPeriodReceiptView, CompanyProfileView, CompanyBankAccountsUpdateView, CompanyBankAccountDeleteView, CompanyBankAccountPrimaryView,
    BuyerListView, BuyerCreateView, BuyerUpdateView, BuyerDetailView, BuyerDeleteView, BuyerQuickCreateView, BuyerQuickUpdateView, BuyerQuickDeleteView, BuyerRateUpdateView, BuyerRateCellSaveView, BuyerRateHistoryDeleteView, BuyerAccountView, BuyerPaymentReceiveView,
    FarmerListView, FarmerBulkRateUpdateView, FarmerBulkRateCellSaveView, FarmerCreateView, FarmerUpdateView, FarmerDetailView, FarmerStatementPrintView, FarmerRateUpdateView, FarmerRateHistoryDeleteView, FarmerDeleteView, FarmerQuickCreateView, FarmerQuickUpdateView, FarmerQuickDeleteView, FarmerBlockerDeleteView, FarmerResignView, FarmerImportExcelView, FarmerImportTemplateView, FarmerBankAccountsUpdateView, FarmerBankAccountDeleteView, FarmerBankAccountPrimaryView, FarmerBankAccountImportExcelView, FarmerBankAccountImportTemplateView,
)
from .route_driver_views import (
    RouteDriverLoginView,
    RouteDriverLogoutView,
    RouteDriverDashboardView,
    RouteDriverRouteSummaryView,
    RouteDriverPointSummaryView,
    RouteDriverFarmerGoodsView,
    RouteDriverGoodsNotificationFeedView,
    RouteDriverFarmerGoodsAcceptView,
    RouteDriverFarmerGoodsRejectView,
    RouteDriverGoodsRequestView,
    RouteDriverFarmerGoodsRequestCreateView,
    RouteDriverFarmerGoodsRequestCancelView,
)

urlpatterns = [
    path('driver/', RouteDriverLoginView.as_view(), name='route-driver-login'),
    path('driver/logout/', RouteDriverLogoutView.as_view(), name='route-driver-logout'),
    path('driver/dashboard/', RouteDriverDashboardView.as_view(), name='route-driver-dashboard'),
    path('driver/notifications/feed/', RouteDriverGoodsNotificationFeedView.as_view(), name='route-driver-goods-notification-feed'),
    path('driver/farmer-goods/<str:batch_ref>/accept/', RouteDriverFarmerGoodsAcceptView.as_view(), name='route-driver-farmer-goods-accept'),
    path('driver/farmer-goods/<str:batch_ref>/reject/', RouteDriverFarmerGoodsRejectView.as_view(), name='route-driver-farmer-goods-reject'),
    path('driver/goods-requests/', RouteDriverGoodsRequestView.as_view(), name='route-driver-goods-request'),
    path('driver/goods-requests/add/', RouteDriverFarmerGoodsRequestCreateView.as_view(), name='route-driver-goods-request-add'),
    path('driver/goods-requests/<int:pk>/cancel/', RouteDriverFarmerGoodsRequestCancelView.as_view(), name='route-driver-goods-request-cancel'),
    path('driver/route-summary/', RouteDriverRouteSummaryView.as_view(), name='route-driver-route-summary'),
    path('driver/point-summary/', RouteDriverPointSummaryView.as_view(), name='route-driver-point-summary'),
    path('driver/farmer-goods/', RouteDriverFarmerGoodsView.as_view(), name='route-driver-farmer-goods'),
    path('routes/', RouteListView.as_view(), name='route-list'),
    path('routes/add/', RouteCreateView.as_view(), name='route-add'),
    path('routes/quick-add/', RouteQuickCreateView.as_view(), name='route-quick-add'),
    path('routes/<int:pk>/quick-edit/', RouteQuickUpdateView.as_view(), name='route-quick-edit'),
    path('routes/<int:pk>/', RouteDetailView.as_view(), name='route-detail'),
    path('routes/<int:pk>/edit/', RouteUpdateView.as_view(), name='route-edit'),
    path('routes/<int:pk>/delete/', RouteDeleteView.as_view(), name='route-delete'),
    path('routes/<int:pk>/points/quick-add/', RouteCollectionPointQuickCreateView.as_view(), name='route-point-quick-add'),
    path('routes/<int:pk>/points/<int:point_id>/quick-edit/', RouteCollectionPointQuickUpdateView.as_view(), name='route-point-quick-edit'),
    path('routes/<int:pk>/points/<int:point_id>/quick-delete/', RouteCollectionPointQuickDeleteView.as_view(), name='route-point-quick-delete'),
    path('routes/<int:pk>/collections/<int:collection_id>/quick-delete/', RouteMilkCollectionQuickDeleteView.as_view(), name='route-collection-quick-delete'),
    path('points/', CollectionPointListView.as_view(), name='point-list'),
    path('company/', CompanyProfileView.as_view(), name='company-profile'),
    path('company/bank-accounts/', CompanyBankAccountsUpdateView.as_view(), name='company-bank-accounts-update'),
    path(
        'company/bank-accounts/<int:account_pk>/delete/',
        CompanyBankAccountDeleteView.as_view(),
        name='company-bank-account-delete',
    ),
    path(
        'company/bank-accounts/<int:account_pk>/primary/',
        CompanyBankAccountPrimaryView.as_view(),
        name='company-bank-account-primary',
    ),
    path('points/add/', CollectionPointCreateView.as_view(), name='point-add'),
    path('points/quick-add/', CollectionPointQuickCreateView.as_view(), name='point-quick-add'),
    path('points/<int:pk>/quick-edit/', CollectionPointQuickUpdateView.as_view(), name='point-quick-edit'),
    path('points/<int:pk>/quick-delete/', CollectionPointQuickDeleteView.as_view(), name='point-quick-delete'),
    path('points/<int:pk>/receipt/period/', CollectionPointPeriodReceiptView.as_view(), name='point-receipt-period'),
    path('points/<int:point_pk>/farmers/<int:farmer_pk>/receipt/period/', FarmerPeriodReceiptView.as_view(), name='farmer-receipt-period'),
    path('points/<int:pk>/additional-farmers/', CollectionPointAdditionalFarmersView.as_view(), name='point-additional-farmers'),
    path('points/fees/cell/', CollectionPointFeeCellSaveView.as_view(), name='point-fee-cell-save'),
    path('points/<int:pk>/fees/', CollectionPointFeeUpdateView.as_view(), name='point-fee-update'),
    path(
        'points/<int:pk>/bank-accounts/',
        CollectionPointBankAccountsUpdateView.as_view(),
        name='point-bank-accounts-update',
    ),
    path(
        'points/<int:pk>/bank-accounts/<int:account_pk>/delete/',
        CollectionPointBankAccountDeleteView.as_view(),
        name='point-bank-account-delete',
    ),
    path(
        'points/<int:pk>/bank-accounts/<int:account_pk>/primary/',
        CollectionPointBankAccountPrimaryView.as_view(),
        name='point-bank-account-primary',
    ),
    path(
        'points/bank-accounts/import/template/',
        CollectionPointBankAccountImportTemplateView.as_view(),
        name='point-bank-account-import-template',
    ),
    path(
        'points/bank-accounts/import/',
        CollectionPointBankAccountImportExcelView.as_view(),
        name='point-bank-account-import',
    ),
    path(
        'points/<int:point_pk>/fee-history/<int:fee_pk>/delete/',
        CollectionPointFeeHistoryDeleteView.as_view(),
        name='point-fee-history-delete',
    ),
    path('points/<int:pk>/statement/', CollectionPointStatementPrintView.as_view(), name='point-statement-print'),
    path('points/<int:pk>/', CollectionPointDetailView.as_view(), name='point-detail'),
    path('points/<int:pk>/edit/', CollectionPointUpdateView.as_view(), name='point-edit'),
    path('buyers/', BuyerListView.as_view(), name='buyer-list'),
    path('buyers/add/', BuyerCreateView.as_view(), name='buyer-add'),
    path('buyers/quick-add/', BuyerQuickCreateView.as_view(), name='buyer-quick-add'),
    path('buyers/<int:pk>/quick-edit/', BuyerQuickUpdateView.as_view(), name='buyer-quick-edit'),
    path('buyers/<int:pk>/quick-delete/', BuyerQuickDeleteView.as_view(), name='buyer-quick-delete'),
    path('buyers/<int:pk>/', BuyerDetailView.as_view(), name='buyer-detail'),
    path('buyers/<int:pk>/rate/', BuyerRateUpdateView.as_view(), name='buyer-rate-update'),
    path('buyers/rate/cell/', BuyerRateCellSaveView.as_view(), name='buyer-rate-cell-save'),
    path(
        'buyers/<int:buyer_pk>/rate-history/<int:rate_pk>/delete/',
        BuyerRateHistoryDeleteView.as_view(),
        name='buyer-rate-history-delete',
    ),
    path('buyers/<int:pk>/account/', BuyerAccountView.as_view(), name='buyer-account'),
    path('buyers/<int:pk>/payments/receive/', BuyerPaymentReceiveView.as_view(), name='buyer-payment-receive'),
    path('buyers/<int:pk>/edit/', BuyerUpdateView.as_view(), name='buyer-edit'),
    path('buyers/<int:pk>/delete/', BuyerDeleteView.as_view(), name='buyer-delete'),
    path('farmers/', FarmerListView.as_view(), name='farmer-list'),
    path('farmers/bulk-rate/', FarmerBulkRateUpdateView.as_view(), name='farmer-bulk-rate-update'),
    path('farmers/bulk-rate/cell/', FarmerBulkRateCellSaveView.as_view(), name='farmer-bulk-rate-cell-save'),
    path('farmers/import/template/', FarmerImportTemplateView.as_view(), name='farmer-import-template'),
    path('farmers/import/', FarmerImportExcelView.as_view(), name='farmer-import'),
    path(
        'farmers/bank-accounts/import/template/',
        FarmerBankAccountImportTemplateView.as_view(),
        name='farmer-bank-account-import-template',
    ),
    path(
        'farmers/bank-accounts/import/',
        FarmerBankAccountImportExcelView.as_view(),
        name='farmer-bank-account-import',
    ),
    path('farmers/add/', FarmerCreateView.as_view(), name='farmer-add'),
    path('farmers/quick-add/', FarmerQuickCreateView.as_view(), name='farmer-quick-add'),
    path('farmers/<int:pk>/quick-edit/', FarmerQuickUpdateView.as_view(), name='farmer-quick-edit'),
    path('farmers/<int:pk>/resign/', FarmerResignView.as_view(), name='farmer-resign'),
    path('farmers/<int:pk>/quick-delete/', FarmerQuickDeleteView.as_view(), name='farmer-quick-delete'),
    path('farmers/<int:pk>/delete-blocker/', FarmerBlockerDeleteView.as_view(), name='farmer-delete-blocker'),
    path('farmers/<int:pk>/statement/', FarmerStatementPrintView.as_view(), name='farmer-statement-print'),
    path(
        'farmers/<int:pk>/bank-accounts/',
        FarmerBankAccountsUpdateView.as_view(),
        name='farmer-bank-accounts-update',
    ),
    path(
        'farmers/<int:pk>/bank-accounts/<int:account_pk>/delete/',
        FarmerBankAccountDeleteView.as_view(),
        name='farmer-bank-account-delete',
    ),
    path(
        'farmers/<int:pk>/bank-accounts/<int:account_pk>/primary/',
        FarmerBankAccountPrimaryView.as_view(),
        name='farmer-bank-account-primary',
    ),
    path('farmers/<int:pk>/', FarmerDetailView.as_view(), name='farmer-detail'),
    path('farmers/<int:pk>/rate/', FarmerRateUpdateView.as_view(), name='farmer-rate-update'),
    path(
        'farmers/<int:farmer_pk>/rate-history/<int:rate_pk>/delete/',
        FarmerRateHistoryDeleteView.as_view(),
        name='farmer-rate-history-delete',
    ),
    path('farmers/<int:pk>/edit/', FarmerUpdateView.as_view(), name='farmer-edit'),
    path('farmers/<int:pk>/delete/', FarmerDeleteView.as_view(), name='farmer-delete'),
]
