# Generated by Django 6.0.3 on 2026-03-28 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milkcollection',
            options={'ordering': ['-date', 'route__code', 'collection_point__number', 'farmer__name']},
        ),
        migrations.RemoveConstraint(
            model_name='milkcollection',
            name='uniq_daily_route_point_collection',
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.farmer'),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='source',
            field=models.CharField(choices=[('point', 'Collection point'), ('farmer', 'Farmer')], default='point', max_length=10),
        ),
        migrations.AlterField(
            model_name='milkcollection',
            name='collection_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.collectionpoint'),
        ),
        migrations.AddConstraint(
            model_name='milkcollection',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'point')), fields=('date', 'route', 'collection_point'), name='uniq_daily_route_point_collection'),
        ),
        migrations.AddConstraint(
            model_name='milkcollection',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'farmer')), fields=('date', 'route', 'farmer'), name='uniq_daily_route_farmer_collection'),
        ),
    ]
