# Generated by Django 6.0.3 on 2026-03-29 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0003_milkcollectionadjustment'),
        ('masters', '0004_farmer_collection_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milkfactor',
            options={'ordering': ['-date', 'route__code', 'collection_point__number', 'farmer__name']},
        ),
        migrations.RemoveConstraint(
            model_name='milkfactor',
            name='uniq_daily_route_point_factor',
        ),
        migrations.AddField(
            model_name='milkfactor',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.farmer'),
        ),
        migrations.AddField(
            model_name='milkfactor',
            name='source',
            field=models.CharField(choices=[('point', 'Collection point'), ('farmer', 'Farmer')], default='point', max_length=10),
        ),
        migrations.AlterField(
            model_name='milkfactor',
            name='collection_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.collectionpoint'),
        ),
        migrations.AddConstraint(
            model_name='milkfactor',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'point')), fields=('date', 'route', 'collection_point'), name='uniq_daily_route_point_factor'),
        ),
        migrations.AddConstraint(
            model_name='milkfactor',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'farmer')), fields=('date', 'route', 'farmer'), name='uniq_daily_route_farmer_factor'),
        ),
    ]
