# Generated by Django 5.2.13 on 2026-04-23 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('collections', '0004_milkfactor_source_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollection',
            name='branch',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='milk_collections', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='milkfactor',
            name='branch',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='milk_factors', to='branches.branch'),
        ),
    ]
