# Generated by Django 5.2.13 on 2026-04-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0005_milkcollection_branch_milkfactor_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milkcollection',
            options={'ordering': ['-date', 'route__code', 'collection_point__number', 'farmer__full_name']},
        ),
        migrations.AlterModelOptions(
            name='milkfactor',
            options={'ordering': ['-date', 'route__code', 'collection_point__number', 'farmer__full_name']},
        ),
    ]
