# Generated by Django 5.2.13 on 2026-06-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0006_alter_milkcollection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollection',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
