# Generated by Django 5.2.13 on 2026-07-16 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0012_milkcollection_tally_sheet_permissions'),
        ('masters', '0023_grant_collectionpointadvance_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPointMilkReconcileSyncSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('previous_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('had_point_row', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('collection_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_reconcile_sync_snapshots', to='masters.collectionpoint')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_reconcile_sync_snapshots', to='masters.route')),
                ('synced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='milk_reconcile_sync_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'collection_point_id'],
                'constraints': [models.UniqueConstraint(fields=('collection_point', 'route', 'date'), name='uniq_collection_point_milk_reconcile_sync_day')],
            },
        ),
    ]
