# Generated by Django 6.0.3 on 2026-03-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Square images work best (e.g. 400×400). Max 2 MB.', null=True, upload_to='avatars/%Y/%m/'),
        ),
    ]
