# Generated by Django 5.2.13 on 2026-05-04 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branchmilkstock'),
        ('suppliers', '0002_grn_discounts_and_line_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Receiving branch / warehouse context for this GRN.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='branches.branch'),
        ),
    ]
