# Generated by Django 5.2.13 on 2026-05-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_grn_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmergoodsissue',
            name='batch_ref',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
    ]
