# Generated by Django 5.2.13 on 2026-05-05 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branchmilkstock'),
        ('suppliers', '0004_farmer_goods_issue_batch_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmergoodsissue',
            name='from_branch',
            field=models.ForeignKey(blank=True, help_text='Branch context for this issue (issuing location).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farmer_goods_issues_from', to='branches.branch'),
        ),
    ]
