# Generated by Django 5.2.13 on 2026-05-08 06:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branchmilkstock'),
        ('suppliers', '0005_farmer_goods_issue_from_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMilkSupplierCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liters', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_milk_supplier_collections', to='branches.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_milk_collections_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(limit_choices_to={'category': 'raw_milk_supplier'}, on_delete=django.db.models.deletion.PROTECT, related_name='raw_milk_collections', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('date', 'branch', 'supplier'), name='uniq_daily_branch_supplier_raw_milk_collection')],
            },
        ),
    ]
