# Generated by Django 5.2.13 on 2026-05-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_rawmilksuppliercollection'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rawmilksuppliercollection',
            name='uniq_daily_branch_supplier_raw_milk_collection',
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='acidity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='alcohol',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='browser_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Browser number'),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='dispatch_no',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='driver',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='In time'),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='kq',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='lr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Out time'),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='Payment status'),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='sealing_numbers',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sealing numbers'),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='snf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='supplier_result_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Supplier result (quantity)'),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperature (°C)'),
        ),
    ]
