# Generated by Django 5.2.13 on 2026-05-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_remove_rawmilksuppliercollection_uniq_daily_branch_supplier_raw_milk_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmilksuppliercollection',
            name='kg',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rawmilksuppliercollection',
            name='liters',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Liters'),
        ),
    ]
