# Generated by Django 5.2.13 on 2026-06-20 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_raw_milk_collection_liters_input'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmilksuppliercollection',
            options={'ordering': ['-date', '-id'], 'permissions': [('view_rawmilkbulkcollection', 'Can view raw milk bulk collection')]},
        ),
    ]
