# Generated by Django 5.2.13 on 2026-06-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_branchmilkstockadjustment'),
        ('suppliers', '0010_grant_raw_milk_bulk_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='branches.branch'),
        ),
    ]
