# Generated by Django 5.2.13 on 2026-06-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0011_buyer_supplier_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmergoodsissue',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmergoodsissue',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
