# Generated by Django 5.2.13 on 2026-08-09 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0015_driver_farmer_goods_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grn',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='farmergoodsissue',
            name='driver_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending driver'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='not_required', help_text='Collection-point issues require accept/reject (route driver, Admin, or Branch Manager) before payment.', max_length=20),
        ),
        migrations.CreateModel(
            name='GRNActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('confirmed', 'Confirmed'), ('reverted_to_draft', 'Reverted to draft'), ('deleted', 'Deleted')], max_length=30)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='suppliers.grn')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grn_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at', '-id'],
            },
        ),
    ]
