# Generated by Django 5.2.13 on 2026-08-09 02:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0016_grn_audit_fields_and_action_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'permissions': [('change_supplierrate', 'Can change raw milk supplier rate')]},
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='billable_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity used for billing (liters or kg per rate_unit).', max_digits=12),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='is_billed',
            field=models.BooleanField(default=False, help_text='True after the payable was posted to the supplier account.'),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='rate_unit',
            field=models.CharField(blank=True, choices=[('liter', 'Per liter'), ('kg', 'Per kg')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='rawmilksuppliercollection',
            name='unit_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Supplier rate applied when this collection was billed.', max_digits=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What we pay this raw-milk supplier (current rate).', max_digits=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rate_unit',
            field=models.CharField(choices=[('liter', 'Per liter'), ('kg', 'Per kg')], default='liter', help_text='Whether the rate applies per liter or per kg.', max_length=10),
        ),
        migrations.CreateModel(
            name='RawMilkSupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_milk_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('ledger_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_milk_payment', to='suppliers.suppliertransaction')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_milk_payments', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_unit', models.CharField(choices=[('liter', 'Per liter'), ('kg', 'Per kg')], default='liter', max_length=10)),
                ('effective_from', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RawMilkSupplierPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='suppliers.rawmilksuppliercollection')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='suppliers.rawmilksupplierpayment')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('payment', 'collection')},
            },
        ),
    ]
