# Generated by Django 5.2.13 on 2026-08-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0018_grant_supplier_rate_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grn',
            name='grn_type',
            field=models.CharField(choices=[('corporate', 'CORPORATE'), ('farmer_goods', 'FARMER_GOODS'), ('stock_correction', 'STOCK CORRECTION')], max_length=20),
        ),
    ]
