# Generated by Django 5.2.13 on 2026-08-11 07:19

from decimal import Decimal

from django.db import migrations, models


def clamp_negative_farmer_goods_stock(apps, schema_editor):
    FarmerGoodsStock = apps.get_model("suppliers", "FarmerGoodsStock")
    FarmerGoodsStock.objects.filter(quantity__lt=0).update(quantity=Decimal("0.00"))


class Migration(migrations.Migration):

    dependencies = [
        ("stock_management", "0009_stock_quantity_non_negative"),
        ("suppliers", "0019_grn_stock_correction_type"),
    ]

    operations = [
        migrations.RunPython(clamp_negative_farmer_goods_stock, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="farmergoodsstock",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="farmergoodsstock_quantity_gte_0",
            ),
        ),
    ]
