# Generated by Django 5.2.13 on 2026-08-17 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("suppliers", "0020_stock_quantity_non_negative"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerGoodsModuleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_accept_notifications",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "When on, collection-point issues wait for Accept before stock and payment. "
                            "When off, issues apply immediately and accept notifications are hidden."
                        ),
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Farmer goods settings",
                "verbose_name_plural": "Farmer goods settings",
            },
        ),
    ]
