# Generated by Django 5.2.13 on 2026-08-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0021_farmergoodsmodulesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmergoodsissue',
            name='driver_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending driver'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='not_required', help_text='Collection-point issues require accept/reject before payment unless accept notifications are disabled.', max_length=20),
        ),
    ]
