# Generated by Django 5.2.13 on 2026-05-06 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_loans', '0002_rename_repayment_period_to_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerloan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerloan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_farmer_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmerloan',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerloan',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_farmer_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmerloan',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
