# Generated by Django 5.2.13 on 2026-06-14 06:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_loans', '0004_loan_dates_and_installments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerloan',
            name='installment_count',
            field=models.PositiveIntegerField(help_text='Total number of instalments (2 per month: 15th and month-end).'),
        ),
        migrations.AlterField(
            model_name='farmerloan',
            name='loan_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
