# Generated by Django 5.2.13 on 2026-06-15 09:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_loans', '0007_farmerloan_requested_installment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerloan',
            name='is_existing_loan',
            field=models.BooleanField(default=False, help_text='Loan already in progress before it was recorded in the system.'),
        ),
        migrations.AddField(
            model_name='farmerloan',
            name='prior_paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount already paid on this loan before system entry.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='farmerloanactionlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('submitted', 'Submitted for approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reverted_to_draft', 'Reverted to draft'), ('schedule_paid_updated', 'Repayment schedule paid amounts updated')], max_length=30),
        ),
    ]
