# Generated by Django 6.0.3 on 2026-03-29 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_farmer_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='collection_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_farmers', to='masters.collectionpoint', verbose_name='collection point'),
        ),
    ]
