# Generated by Django 5.2.13 on 2026-04-23 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('masters', '0004_farmer_collection_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farmers', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='route',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='branches.branch'),
        ),
    ]
