# Generated by Django 5.2.13 on 2026-04-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_farmer_branch_route_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmer',
            options={'ordering': ['common_name', 'full_name', 'name']},
        ),
        migrations.AddField(
            model_name='farmer',
            name='common_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmer',
            name='full_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='farmer',
            name='initial',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='farmer',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Leave blank to assign automatically (FAR + id).', max_length=50, null=True, unique=True),
        ),
    ]
