# Generated by Django 5.2.13 on 2026-05-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_remove_farmer_name_and_require_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='apply_rate_paid',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='farmer',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
