# Generated by Django 5.2.13 on 2026-05-08 10:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_farmer_rate_history(apps, schema_editor):
    Farmer = apps.get_model("masters", "Farmer")
    FarmerRateHistory = apps.get_model("masters", "FarmerRateHistory")
    now = django.utils.timezone.now()
    rows = []
    for farmer in Farmer.objects.all().only("id", "rate", "apply_rate_paid"):
        rows.append(
            FarmerRateHistory(
                farmer_id=farmer.id,
                rate=farmer.rate,
                apply_rate_paid=farmer.apply_rate_paid or "yes",
                effective_at=now,
            )
        )
    if rows:
        FarmerRateHistory.objects.bulk_create(rows, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_farmer_apply_rate_paid_farmer_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apply_rate_paid', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3)),
                ('effective_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='masters.farmer')),
            ],
            options={
                'ordering': ['-effective_at', '-id'],
            },
        ),
        migrations.RunPython(seed_farmer_rate_history, migrations.RunPython.noop),
    ]
