# Generated by Django 5.2.13 on 2026-06-20 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_farmeradvancepayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmerratehistory',
            options={'ordering': ['-effective_at', '-id'], 'permissions': [('change_farmerrate', 'Can change farmer rate'), ('bulk_update_farmerrate', 'Can bulk update farmer rates')]},
        ),
    ]
