# Generated by Django 5.2.13 on 2026-06-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_branchmilkstockadjustment'),
        ('masters', '0012_grant_farmer_rate_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='buyers', to='branches.branch'),
        ),
    ]
