# Generated by Django 5.2.13 on 2026-06-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_assign_buyer_supplier_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='collector_fee',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Collector fee'),
        ),
    ]
