# Generated by Django 5.2.13 on 2026-06-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_collectionpoint_collector_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmeradvancepayment',
            name='is_recovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmeradvancepayment',
            name='recovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
