# Generated by Django 5.2.13 on 2026-07-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0023_grant_collectionpointadvance_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='additional_farmers',
            field=models.ManyToManyField(blank=True, help_text='Farmers whose milk totals are used for Additional. Leave empty to use all farmers at this point.', related_name='additional_basis_collection_points', to='masters.farmer'),
        ),
    ]
