# Generated by Django 5.2.13 on 2026-08-09 02:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_advance_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current buying rate paid to us.', max_digits=10),
        ),
        migrations.AddField(
            model_name='buyer',
            name='rate_unit',
            field=models.CharField(choices=[('liter', 'Per liter'), ('kg', 'Per kg')], default='liter', help_text='Whether the rate applies per liter or per kg.', max_length=10),
        ),
        migrations.CreateModel(
            name='BuyerRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_unit', models.CharField(choices=[('liter', 'Per liter'), ('kg', 'Per kg')], default='liter', max_length=10)),
                ('effective_from', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='masters.buyer')),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
                'permissions': [('change_buyerrate', 'Can change buyer rate')],
            },
        ),
    ]
