# Generated by Django 5.2.13 on 2026-08-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0029_advance_previous_outstanding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmeradvancepayment",
            name="advance_type",
            field=models.CharField(
                choices=[
                    ("advance", "Advance Payment"),
                    ("bank_loan", "Bank Loan Deduction"),
                ],
                default="advance",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="collectionpointadvancepayment",
            name="advance_type",
            field=models.CharField(
                choices=[
                    ("advance", "Advance Payment"),
                    ("bank_loan", "Bank Loan Deduction"),
                ],
                default="advance",
                max_length=20,
            ),
        ),
    ]
