# Generated by Django 5.2.13 on 2026-08-19 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0031_collectionpointadvance_partial_recovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPointBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account_name', models.CharField(max_length=120, verbose_name='Account name')),
                ('account_number', models.CharField(max_length=40, verbose_name='Account number')),
                ('bank_name', models.CharField(max_length=120, verbose_name='Bank')),
                ('bank_branch', models.CharField(max_length=120, verbose_name='Branch')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary')),
                ('collection_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='masters.collectionpoint')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
    ]
