# Generated by Django 5.2.13 on 2026-08-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0033_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='code',
            field=models.CharField(blank=True, help_text='CEFT / SLIPS bank code (e.g. 7010).', max_length=10, verbose_name='Bank code'),
        ),
        migrations.AddField(
            model_name='collectionpointbankaccount',
            name='bank_code',
            field=models.CharField(blank=True, help_text='Beneficiary bank code for CEFT upload (e.g. 7010).', max_length=10, verbose_name='Bank code'),
        ),
        migrations.AddField(
            model_name='collectionpointbankaccount',
            name='branch_code',
            field=models.CharField(blank=True, help_text='Beneficiary branch code for CEFT upload (e.g. 048).', max_length=10, verbose_name='Branch code'),
        ),
    ]
