# Generated by Django 5.2.13 on 2026-08-21 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0034_bank_account_ceft_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account_name', models.CharField(max_length=120, verbose_name='Account name')),
                ('account_number', models.CharField(max_length=40, verbose_name='Account number')),
                ('bank_name', models.CharField(max_length=120, verbose_name='Bank')),
                ('bank_code', models.CharField(blank=True, help_text='Beneficiary bank code for CEFT upload (e.g. 7010).', max_length=10, verbose_name='Bank code')),
                ('bank_branch', models.CharField(max_length=120, verbose_name='Branch')),
                ('branch_code', models.CharField(blank=True, help_text='Beneficiary branch code for CEFT upload (e.g. 048).', max_length=10, verbose_name='Branch code')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='masters.farmer')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
    ]
