# Generated by Django 5.2.13 on 2026-08-21 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0035_farmer_bank_accounts_and_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(default='CANMEE DAIRIES (PVT) LTD', max_length=160, verbose_name='Company name')),
                ('legal_name', models.CharField(blank=True, max_length=160, verbose_name='Legal name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('tax_id', models.CharField(blank=True, max_length=60, verbose_name='Tax / VAT ID')),
                ('website', models.CharField(blank=True, max_length=120, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Company profile',
                'verbose_name_plural': 'Company profile',
            },
        ),
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account_name', models.CharField(max_length=120, verbose_name='Account name')),
                ('account_number', models.CharField(max_length=40, verbose_name='Account number')),
                ('bank_name', models.CharField(max_length=120, verbose_name='Bank')),
                ('bank_code', models.CharField(blank=True, max_length=10, verbose_name='Bank code')),
                ('bank_branch', models.CharField(blank=True, max_length=120, verbose_name='Branch')),
                ('branch_code', models.CharField(blank=True, max_length=10, verbose_name='Branch code')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='masters.companyprofile')),
            ],
            options={
                'verbose_name': 'Company bank account',
                'verbose_name_plural': 'Company bank accounts',
                'ordering': ['-is_primary', 'id'],
            },
        ),
    ]
