# Generated by Django 5.2.13 on 2026-08-14 08:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0007_branch_details'),
        ('hrm', '0007_employee_attendance_password_set'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepreciationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('method', models.CharField(choices=[('straight_line', 'Straight line'), ('reducing_balance', 'Reducing balance')], default='straight_line', max_length=30)),
                ('useful_life_months', models.PositiveIntegerField(default=60, help_text='Default useful life in months.')),
                ('residual_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Residual / salvage as % of cost.', max_digits=6)),
                ('annual_rate_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Used for reducing-balance method (annual %).', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Depreciation policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='assets.assetcategory')),
            ],
            options={
                'verbose_name_plural': 'Asset categories',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(db_index=True, help_text='Unique label / barcode tag.', max_length=60, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_storage', 'In storage'), ('under_maintenance', 'Under maintenance'), ('disposed', 'Disposed'), ('lost', 'Lost'), ('transferred', 'Transferred')], db_index=True, default='active', max_length=30)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='good', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model_number', models.CharField(blank=True, max_length=120)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Book / market value after valuations & depreciation.', max_digits=14)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('useful_life_months', models.PositiveIntegerField(blank=True, help_text='Override policy useful life (months).', null=True)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disposed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Blank = Main (shared / HO).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodied_assets', to='hrm.employee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('manage_asset_settings', 'Can manage asset module settings'), ('run_asset_depreciation', 'Can run asset depreciation'), ('verify_assets', 'Can verify and value assets'), ('print_asset_labels', 'Can generate asset labels')],
            },
        ),
        migrations.CreateModel(
            name='AssetLabelBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label_count', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('assets', models.ManyToManyField(blank=True, related_name='label_batches', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Asset label batches',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Blank = shared / main (all branches).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_locations', to='branches.branch')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_locations', to='assets.assetlocation')),
            ],
            options={
                'verbose_name': 'Asset location',
                'verbose_name_plural': 'Asset locations',
                'ordering': ['branch__name', 'name', 'id'],
                'unique_together': {('branch', 'code')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetlocation'),
        ),
        migrations.CreateModel(
            name='AssetModuleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_depreciation', models.BooleanField(default=False, help_text='When enabled, depreciation policies and run schedules are available.')),
                ('default_label_prefix', models.CharField(blank=True, default='AST', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset module settings',
                'verbose_name_plural': 'Asset module settings',
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='assets.asset')),
                ('from_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='branches.branch')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.assetlocation')),
                ('to_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='branches.branch')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.assetlocation')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transferred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valued_at', models.DateField(default=django.utils.timezone.localdate)),
                ('previous_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='assets.asset')),
                ('valued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-valued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('found', 'Found'), ('missing', 'Missing'), ('damaged', 'Damaged'), ('relocated', 'Relocated')], default='found', max_length=20)),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], max_length=20)),
                ('assessed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('note', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='assets.asset')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.assetlocation')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verified_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.depreciationpolicy'),
        ),
        migrations.CreateModel(
            name='AssetDepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('book_value_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('book_value_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='assets.asset')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='assets.depreciationpolicy')),
            ],
            options={
                'verbose_name_plural': 'Asset depreciation entries',
                'ordering': ['-period_end', '-id'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'period_start', 'period_end'), name='uniq_asset_depr_period')],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['branch', 'status'], name='assets_asse_branch__55c94e_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category', 'status'], name='assets_asse_categor_c15078_idx'),
        ),
    ]
