# Generated by Django 5.2.13 on 2026-08-14 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('branches', '0007_branch_details'),
        ('hrm', '0007_employee_attendance_password_set'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('current', 'Current Asset'), ('fixed', 'Fixed Asset'), ('fixtures_fittings', 'Fixtures & Fittings'), ('memorandum', 'Memorandum Asset')], db_index=True, default='fixed', max_length=30, verbose_name='Type'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type', 'status'], name='assets_asse_asset_t_be4ea2_idx'),
        ),
    ]
