# Generated by Django 5.2.13 on 2026-08-14 23:20

from django.db import migrations, models
import django.db.models.deletion


TYPE_ROWS = [
    ("current", "Current Asset", 10),
    ("fixed", "Fixed Asset", 20),
    ("fixtures_fittings", "Fixtures & Fittings", 30),
    ("memorandum", "Memorandum Asset", 40),
]

CATEGORIES_BY_TYPE = {
    "current": [
        ("CURRENT-FD", "Fixed Deposits"),
        ("CURRENT-SW", "Software"),
    ],
    "fixed": [
        ("FIXED-BLD", "Building"),
        ("FIXED-BFA", "Building Fittings & Other Accessories"),
        ("FIXED-CAM", "Camera"),
        ("FIXED-COMP", "Computers & Computer Accessories"),
        ("FIXED-FUR", "Furniture And Fittings"),
        ("FIXED-GH", "Green House"),
        ("FIXED-LAND", "Land"),
        ("FIXED-LAP", "Laptops"),
        ("FIXED-VEH", "Motor Vehicle"),
        ("FIXED-OE", "Office Equipment"),
        ("FIXED-PM", "Plant and Machineries"),
        ("FIXED-TOOL", "Tools & Equipment"),
    ],
}


def seed_types_and_categories(apps, schema_editor):
    AssetType = apps.get_model("assets", "AssetType")
    AssetCategory = apps.get_model("assets", "AssetCategory")
    Asset = apps.get_model("assets", "Asset")

    types = {}
    for code, name, sort_order in TYPE_ROWS:
        obj, _ = AssetType.objects.get_or_create(
            code=code,
            defaults={"name": name, "sort_order": sort_order, "is_active": True},
        )
        types[code] = obj

    fallback = types["fixed"]

    for type_code, rows in CATEGORIES_BY_TYPE.items():
        asset_type = types[type_code]
        for code, name in rows:
            existing = AssetCategory.objects.filter(models.Q(code=code) | models.Q(name=name)).first()
            if existing:
                if not existing.asset_type_id:
                    existing.asset_type_id = asset_type.pk
                    existing.save(update_fields=["asset_type"])
                continue
            AssetCategory.objects.create(
                code=code,
                name=name,
                asset_type_id=asset_type.pk,
                is_active=True,
            )

    AssetCategory.objects.filter(asset_type_id__isnull=True).update(asset_type_id=fallback.pk)

    code_map = {code: obj.pk for code, obj in types.items()}
    for row in Asset.objects.all().only("id", "asset_type_code"):
        type_id = code_map.get(row.asset_type_code) or fallback.pk
        Asset.objects.filter(pk=row.id).update(asset_type_id=type_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_asset_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Asset type",
                "verbose_name_plural": "Asset types",
                "ordering": ["sort_order", "name", "id"],
            },
        ),
        migrations.RemoveIndex(
            model_name="asset",
            name="assets_asse_asset_t_be4ea2_idx",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="asset_type",
            new_name="asset_type_code",
        ),
        migrations.AddField(
            model_name="asset",
            name="asset_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="assets.assettype",
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="assetcategory",
            name="asset_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="assets.assettype",
            ),
        ),
        migrations.RunPython(seed_types_and_categories, noop_reverse),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="assets.assettype",
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="assetcategory",
            name="asset_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="assets.assettype",
            ),
        ),
        migrations.RemoveField(
            model_name="asset",
            name="asset_type_code",
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["asset_type", "status"], name="assets_asse_asset_t_be4ea2_idx"),
        ),
        migrations.AlterModelOptions(
            name="assetcategory",
            options={"ordering": ["asset_type__sort_order", "name", "id"], "verbose_name_plural": "Asset categories"},
        ),
    ]
