# Generated by Django 5.2.13 on 2026-08-14 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_managed_asset_types'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asset',
            new_name='assets_asse_asset_t_52eab5_idx',
            old_name='assets_asse_asset_t_be4ea2_idx',
        ),
    ]
