from django.urls import path
from .views import (
    SummaryView, BuyerSummaryView, ExportCollectionCSVView, ExportCollectionExcelView,
    ExportCollectionPDFView, ImportCollectionView, ImportDistributionView, overall_dashboard,
    FarmerPaymentSheetView, FarmerPaymentSheetExcelView, FarmerPaymentSheetPDFView,
    FarmerPaymentSheetBankFileView,
    PaidFarmerPaymentSheetListView,
    CollectionPointPaymentSheetView, CollectionPointPaymentSheetExcelView, CollectionPointPaymentSheetPDFView,
    CollectionPointPaymentSheetBankFileView,
    PaidCollectionPointPaymentSheetListView,
    PointReconcileReportView, PointReconcileReportExcelView, PointReconcileReportPDFView,
    FarmerGoodsSummaryReportView, FarmerGoodsSummaryReportExcelView, FarmerGoodsSummaryReportPDFView,
    FarmerGoodsSummarySlipPrintView,
    PointGoodsSummaryReportView, PointGoodsSummaryReportExcelView, PointGoodsSummaryReportPDFView,
    PointGoodsSummarySlipPrintView,
    CollectionPointPaySlipView, CollectionPointPaySlipBulkPrintView,
    FarmerPaySlipView, FarmerPaySlipBulkPrintView, FarmerAdvancePaymentListView, FarmerAdvancePaymentCreateView,
    FarmerAdvancePaymentUpdateView, FarmerAdvancePaymentDeleteView,
    FarmerAdvancePaymentEmbedView,
    FarmerAdvanceManualSettleView,
    CollectionPointAdvancePaymentListView,
    CollectionPointAdvancePaymentCreateView,
    CollectionPointAdvancePaymentUpdateView,
    CollectionPointAdvancePaymentDeleteView,
    CollectionPointAdvanceManualSettleView,
    CollectionPointAdvanceBalanceView,
    FarmerPaymentLoanDeductionToggleView,
    FarmerPaymentDeductionPickerView,
    FarmerPaymentDeductionSkipToggleView,
    FarmerPeriodPaymentRecordView,
    FarmerBulkPeriodPaymentRecordView,
    CollectionPointPeriodPaymentRecordView,
    CollectionPointBulkPeriodPaymentRecordView,
    CollectionPointPaymentDeductionPickerView,
    CollectionPointPaymentDeductionSkipToggleView,
    CollectionPointPaymentLoanDeductionToggleView,
    CollectionPointPaymentCorrectionSaveView,
)

urlpatterns = [
    path('summary/', SummaryView.as_view(), name='summary'),
    path('buyer-summary/', BuyerSummaryView.as_view(), name='buyer-summary'),
    path('overall/', overall_dashboard, name='overall-dashboard'),
    path('export/csv/', ExportCollectionCSVView.as_view(), name='export-csv'),
    path('export/excel/', ExportCollectionExcelView.as_view(), name='export-excel'),
    path('export/pdf/', ExportCollectionPDFView.as_view(), name='export-pdf'),
    path('import/collections/', ImportCollectionView.as_view(), name='import-collections'),
    path('import/distributions/', ImportDistributionView.as_view(), name='import-distributions'),
    path('farmer-payment-sheet/', FarmerPaymentSheetView.as_view(), name='farmer-payment-sheet'),
    path(
        'farmer-payment-sheet/paid/',
        PaidFarmerPaymentSheetListView.as_view(),
        name='paid-farmer-payment-sheet-list',
    ),
    path(
        'farmer-payment-sheet/export/excel/',
        FarmerPaymentSheetExcelView.as_view(),
        name='farmer-payment-sheet-export-excel',
    ),
    path(
        'farmer-payment-sheet/export/bank-file/',
        FarmerPaymentSheetBankFileView.as_view(),
        name='farmer-payment-sheet-export-bank-file',
    ),
    path(
        'farmer-payment-sheet/export/pdf/',
        FarmerPaymentSheetPDFView.as_view(),
        name='farmer-payment-sheet-export-pdf',
    ),
    path(
        'collection-point-payment-sheet/',
        CollectionPointPaymentSheetView.as_view(),
        name='collection-point-payment-sheet',
    ),
    path(
        'collection-point-payment-sheet/paid/',
        PaidCollectionPointPaymentSheetListView.as_view(),
        name='paid-collection-point-payment-sheet-list',
    ),
    path(
        'collection-point-payment-sheet/export/excel/',
        CollectionPointPaymentSheetExcelView.as_view(),
        name='collection-point-payment-sheet-export-excel',
    ),
    path(
        'collection-point-payment-sheet/export/bank-file/',
        CollectionPointPaymentSheetBankFileView.as_view(),
        name='collection-point-payment-sheet-export-bank-file',
    ),
    path(
        'collection-point-payment-sheet/export/pdf/',
        CollectionPointPaymentSheetPDFView.as_view(),
        name='collection-point-payment-sheet-export-pdf',
    ),
    path('point-reconcile-report/', PointReconcileReportView.as_view(), name='point-reconcile-report'),
    path(
        'point-reconcile-report/export/excel/',
        PointReconcileReportExcelView.as_view(),
        name='point-reconcile-report-export-excel',
    ),
    path(
        'point-reconcile-report/export/pdf/',
        PointReconcileReportPDFView.as_view(),
        name='point-reconcile-report-export-pdf',
    ),
    path('farmer-goods-summary/', FarmerGoodsSummaryReportView.as_view(), name='farmer-goods-summary-report'),
    path(
        'farmer-goods-summary/print-slip/',
        FarmerGoodsSummarySlipPrintView.as_view(),
        name='farmer-goods-summary-slip-print',
    ),
    path(
        'farmer-goods-summary/export/excel/',
        FarmerGoodsSummaryReportExcelView.as_view(),
        name='farmer-goods-summary-report-export-excel',
    ),
    path(
        'farmer-goods-summary/export/pdf/',
        FarmerGoodsSummaryReportPDFView.as_view(),
        name='farmer-goods-summary-report-export-pdf',
    ),
    path('point-goods-summary/', PointGoodsSummaryReportView.as_view(), name='point-goods-summary-report'),
    path(
        'point-goods-summary/print-slip/',
        PointGoodsSummarySlipPrintView.as_view(),
        name='point-goods-summary-slip-print',
    ),
    path(
        'point-goods-summary/export/excel/',
        PointGoodsSummaryReportExcelView.as_view(),
        name='point-goods-summary-report-export-excel',
    ),
    path(
        'point-goods-summary/export/pdf/',
        PointGoodsSummaryReportPDFView.as_view(),
        name='point-goods-summary-report-export-pdf',
    ),
    path('collection-point-payslip/<int:pk>/', CollectionPointPaySlipView.as_view(), name='collection-point-payslip'),
    path('collection-point-payslip-bulk/', CollectionPointPaySlipBulkPrintView.as_view(), name='collection-point-payslip-bulk'),
    path('farmer-advances/', FarmerAdvancePaymentListView.as_view(), name='farmer-advance-list'),
    path('farmer-advances/add/', FarmerAdvancePaymentCreateView.as_view(), name='farmer-advance-add'),
    path('farmer-advances/<int:pk>/edit/', FarmerAdvancePaymentUpdateView.as_view(), name='farmer-advance-edit'),
    path('farmer-advances/<int:pk>/embed/', FarmerAdvancePaymentEmbedView.as_view(), name='farmer-advance-embed'),
    path('farmer-advances/<int:pk>/delete/', FarmerAdvancePaymentDeleteView.as_view(), name='farmer-advance-delete'),
    path(
        'farmer-advances/<int:pk>/manual-settle/',
        FarmerAdvanceManualSettleView.as_view(),
        name='farmer-advance-manual-settle',
    ),
    path(
        'collection-point-advances/',
        CollectionPointAdvancePaymentListView.as_view(),
        name='collection-point-advance-list',
    ),
    path(
        'collection-point-advances/balance/',
        CollectionPointAdvanceBalanceView.as_view(),
        name='collection-point-advance-balance',
    ),
    path(
        'collection-point-advances/add/',
        CollectionPointAdvancePaymentCreateView.as_view(),
        name='collection-point-advance-add',
    ),
    path(
        'collection-point-advances/<int:pk>/edit/',
        CollectionPointAdvancePaymentUpdateView.as_view(),
        name='collection-point-advance-edit',
    ),
    path(
        'collection-point-advances/<int:pk>/delete/',
        CollectionPointAdvancePaymentDeleteView.as_view(),
        name='collection-point-advance-delete',
    ),
    path(
        'collection-point-advances/<int:pk>/manual-settle/',
        CollectionPointAdvanceManualSettleView.as_view(),
        name='collection-point-advance-manual-settle',
    ),
    path(
        'farmer-payment-sheet/loan-deduction/toggle/',
        FarmerPaymentLoanDeductionToggleView.as_view(),
        name='farmer-payment-loan-deduction-toggle',
    ),
    path(
        'farmer-payment-sheet/deductions/picker/',
        FarmerPaymentDeductionPickerView.as_view(),
        name='farmer-payment-deduction-picker',
    ),
    path(
        'farmer-payment-sheet/deductions/toggle/',
        FarmerPaymentDeductionSkipToggleView.as_view(),
        name='farmer-payment-deduction-skip-toggle',
    ),
    path(
        'farmer-payment-sheet/record-payment/',
        FarmerPeriodPaymentRecordView.as_view(),
        name='farmer-period-payment-record',
    ),
    path(
        'farmer-payment-sheet/record-payment/bulk/',
        FarmerBulkPeriodPaymentRecordView.as_view(),
        name='farmer-bulk-period-payment-record',
    ),
    path(
        'collection-point-payment-sheet/record-payment/',
        CollectionPointPeriodPaymentRecordView.as_view(),
        name='collection-point-period-payment-record',
    ),
    path(
        'collection-point-payment-sheet/record-payment/bulk/',
        CollectionPointBulkPeriodPaymentRecordView.as_view(),
        name='collection-point-bulk-period-payment-record',
    ),
    path(
        'collection-point-payment-sheet/loan-deduction/toggle/',
        CollectionPointPaymentLoanDeductionToggleView.as_view(),
        name='collection-point-payment-loan-deduction-toggle',
    ),
    path(
        'collection-point-payment-sheet/payment-correction/',
        CollectionPointPaymentCorrectionSaveView.as_view(),
        name='collection-point-payment-correction-save',
    ),
    path(
        'collection-point-payment-sheet/deductions/picker/',
        CollectionPointPaymentDeductionPickerView.as_view(),
        name='collection-point-payment-deduction-picker',
    ),
    path(
        'collection-point-payment-sheet/deductions/toggle/',
        CollectionPointPaymentDeductionSkipToggleView.as_view(),
        name='collection-point-payment-deduction-skip-toggle',
    ),
    path('farmer-payslip/<int:pk>/', FarmerPaySlipView.as_view(), name='farmer-payslip'),
    path('farmer-payslip-bulk/', FarmerPaySlipBulkPrintView.as_view(), name='farmer-payslip-bulk'),
]
