from django.urls import path

from .views import (
    BranchStockListAPI,
    MainStockListAPI,
    ProductCreateAPI,
    ProductCategoryCreateView,
    ProductCategoryDeleteView,
    ProductCategoryUpdateView,
    ProductDeleteView,
    ProductCreateView,
    ProductGrnModalAPI,
    ProductStatusUpdateView,
    ProductStockHistoryModalAPI,
    ProductSummaryModalAPI,
    ProductUpdateView,
    StockCountCreateView,
    StockCountDeleteView,
    StockCountEditView,
    StockCountListView,
    StockCountPrintView,
    StockHistoryExportView,
    StockHistoryView,
    StockIssueAPI,
    StockIssueView,
    CorrectNegativeBranchStockView,
    StockLogDocumentModalAPI,
    StockOverviewView,
    StockTransferAPI,
    StockTransferNoteCreateView,
    StockTransferNoteDeleteView,
    StockTransferNoteListView,
    StockTransferNotePrintView,
    StockTransferNoteUpdateView,
)

urlpatterns = [
    path("", StockOverviewView.as_view(), name="stock-overview"),
    path("products/add/", ProductCreateView.as_view(), name="stock-product-add"),
    path("products/<int:pk>/edit/", ProductUpdateView.as_view(), name="stock-product-edit"),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="stock-product-delete"),
    path("products/<int:pk>/status/", ProductStatusUpdateView.as_view(), name="stock-product-status-update"),
    path("categories/create/", ProductCategoryCreateView.as_view(), name="stock-category-create"),
    path("categories/<int:pk>/edit/", ProductCategoryUpdateView.as_view(), name="stock-category-edit"),
    path("categories/<int:pk>/delete/", ProductCategoryDeleteView.as_view(), name="stock-category-delete"),
    path("transfer/", StockTransferNoteCreateView.as_view(), name="stock-transfer"),
    path("transfer/notes/", StockTransferNoteListView.as_view(), name="stock-transfer-note-list"),
    path("transfer/<int:pk>/edit/", StockTransferNoteUpdateView.as_view(), name="stock-transfer-note-edit"),
    path("transfer/<int:pk>/print/", StockTransferNotePrintView.as_view(), name="stock-transfer-note-print"),
    path("transfer/<int:pk>/delete/", StockTransferNoteDeleteView.as_view(), name="stock-transfer-note-delete"),
    path("count/", StockCountListView.as_view(), name="stock-count-list"),
    path("count/new/", StockCountCreateView.as_view(), name="stock-count-create"),
    path("count/<int:pk>/", StockCountEditView.as_view(), name="stock-count-edit"),
    path("count/<int:pk>/print/", StockCountPrintView.as_view(), name="stock-count-print"),
    path("count/<int:pk>/delete/", StockCountDeleteView.as_view(), name="stock-count-delete"),
    path("issue/", StockIssueView.as_view(), name="stock-issue"),
    path("history/", StockHistoryView.as_view(), name="stock-history"),
    path("history/export/", StockHistoryExportView.as_view(), name="stock-history-export"),
    path(
        "correct-negative/",
        CorrectNegativeBranchStockView.as_view(),
        name="stock-correct-negative",
    ),
    path(
        "history/logs/<int:pk>/document-modal/",
        StockLogDocumentModalAPI.as_view(),
        name="stock-log-document-modal",
    ),
    path(
        "history/document-modal/",
        StockLogDocumentModalAPI.as_view(),
        name="stock-history-document-modal",
    ),
    path(
        "products/<int:product_id>/summary-modal/",
        ProductSummaryModalAPI.as_view(),
        name="stock-product-summary-modal",
    ),
    path(
        "products/<int:product_id>/history-modal/",
        ProductStockHistoryModalAPI.as_view(),
        name="stock-product-history-modal",
    ),
    path(
        "products/<int:product_id>/grn-modal/",
        ProductGrnModalAPI.as_view(),
        name="stock-product-grn-modal",
    ),
    path("api/products/", ProductCreateAPI.as_view(), name="api-stock-product-create"),
    path("api/transfers/", StockTransferAPI.as_view(), name="api-stock-transfer"),
    path("api/issues/", StockIssueAPI.as_view(), name="api-stock-issue"),
    path("api/main-stock/", MainStockListAPI.as_view(), name="api-main-stock-list"),
    path("api/branch-stock/", BranchStockListAPI.as_view(), name="api-branch-stock-list"),
]
