from django.urls import path
from .views import (
    MilkCollectionAdjustmentHistoryView,
    MilkCollectionAdjustView,
    MilkCollectionInlineQuantityView,
    MilkCollectionListView,
    MilkCollectionPointTransferView,
    MilkCollectionPointReconcileSyncView,
    MilkCollectionPointReconcileReverseSyncView,
    MilkCollectionReconcileChoiceView,
    MilkCollectionRouteReceiptPrintView,
    MilkCollectionRoutePeriodReceiptView,
    MilkCollectionPointSummaryPrintView,
    MilkCollectionRouteSummaryPrintView,
    MilkCollectionBranchSummaryPrintView,
    MilkCollectionDaySummaryPrintView,
    MilkCollectionPointReceiptPrintView,
    MilkCollectionTodayHistoryJsonView,
    MilkFactorDuplicateCheckView,
    MilkCollectionCreateView,
    MilkCollectionUpdateView,
    MilkCollectionTallyCellSaveView,
    MilkCollectionTallySheetView,
    MilkFactorListView,
    MilkFactorCreateView,
    MilkFactorUpdateView,
)

urlpatterns = [
    path('milk/', MilkCollectionListView.as_view(), name='milk-collection-list'),
    path(
        'milk/transfer-point/',
        MilkCollectionPointTransferView.as_view(),
        name='milk-collection-transfer-point',
    ),
    path(
        'milk/reconcile/sync/',
        MilkCollectionPointReconcileSyncView.as_view(),
        name='milk-collection-reconcile-sync',
    ),
    path(
        'milk/reconcile/reverse-sync/',
        MilkCollectionPointReconcileReverseSyncView.as_view(),
        name='milk-collection-reconcile-reverse-sync',
    ),
    path(
        'milk/reconcile/choice/',
        MilkCollectionReconcileChoiceView.as_view(),
        name='milk-collection-reconcile-choice',
    ),
    path(
        'milk/receipt/route/',
        MilkCollectionRouteReceiptPrintView.as_view(),
        name='milk-collection-route-receipt',
    ),
    path(
        'milk/receipt/route-period/',
        MilkCollectionRoutePeriodReceiptView.as_view(),
        name='milk-collection-route-period-receipt',
    ),
    path(
        'milk/receipt/point-summary/',
        MilkCollectionPointSummaryPrintView.as_view(),
        name='milk-collection-point-summary-receipt',
    ),
    path(
        'milk/receipt/route-summary/',
        MilkCollectionRouteSummaryPrintView.as_view(),
        name='milk-collection-route-summary-receipt',
    ),
    path(
        'milk/receipt/branch-summary/',
        MilkCollectionBranchSummaryPrintView.as_view(),
        name='milk-collection-branch-summary-receipt',
    ),
    path(
        'milk/receipt/day-summary/',
        MilkCollectionDaySummaryPrintView.as_view(),
        name='milk-collection-day-summary-receipt',
    ),
    path(
        'milk/receipt/point/',
        MilkCollectionPointReceiptPrintView.as_view(),
        name='milk-collection-point-receipt',
    ),
    path(
        'milk/today-history-json/',
        MilkCollectionTodayHistoryJsonView.as_view(),
        name='milk-collection-today-history-json',
    ),
    path(
        'factors/duplicate-check/',
        MilkFactorDuplicateCheckView.as_view(),
        name='milk-factor-duplicate-check',
    ),
    path('milk/add/', MilkCollectionCreateView.as_view(), name='milk-collection-add'),
    path('milk/tally/', MilkCollectionTallySheetView.as_view(), name='milk-collection-tally'),
    path('milk/tally/cell/', MilkCollectionTallyCellSaveView.as_view(), name='milk-collection-tally-cell'),
    path('milk/<int:pk>/adjust/', MilkCollectionAdjustView.as_view(), name='milk-collection-adjust'),
    path('milk/<int:pk>/inline-qty/', MilkCollectionInlineQuantityView.as_view(), name='milk-collection-inline-qty'),
    path('milk/<int:pk>/adjustments/', MilkCollectionAdjustmentHistoryView.as_view(), name='milk-collection-adjustments'),
    path('milk/<int:pk>/edit/', MilkCollectionUpdateView.as_view(), name='milk-collection-edit'),
    path('factors/', MilkFactorListView.as_view(), name='milk-factor-list'),
    path('factors/add/', MilkFactorCreateView.as_view(), name='milk-factor-add'),
    path('factors/<int:pk>/edit/', MilkFactorUpdateView.as_view(), name='milk-factor-edit'),
]
