# Generated by Django 5.2.13 on 2026-04-23 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('dispatch', '0003_milkdistribution_browser_and_dispatch_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkdistribution',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='milk_distributions', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='milkdistribution',
            name='browser_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Browser number'),
        ),
    ]
