# Generated by Django 5.2.13 on 2026-05-19 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_distribution_return_status'),
        ('dispatch', '0004_milkdistribution_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkdistribution',
            name='returned_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='milk_distribution_returns', to='branches.branch', verbose_name='Returned branch'),
        ),
        migrations.AlterField(
            model_name='milkdistribution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('return', 'Return'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
