# Generated by Django 5.2.13 on 2026-05-19 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_distribution_return_status'),
        ('dispatch', '0005_distribution_return_status'),
        ('masters', '0010_farmeradvancepayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milkdistribution',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='milkdistribution',
            name='destination_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='milk_distributions_received', to='branches.branch', verbose_name='Destination branch'),
        ),
        migrations.AlterField(
            model_name='milkdistribution',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.buyer'),
        ),
    ]
