# Generated by Django 5.2.13 on 2026-07-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0014_backfill_buyer_return_received_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchnotification',
            name='kind',
            field=models.CharField(choices=[('incoming_dispatch', 'Incoming dispatch'), ('destination_responded', 'Destination responded'), ('return_requested', 'Return requested'), ('return_resolved', 'Return resolved'), ('return_received', 'Return received')], max_length=32),
        ),
    ]
