# Generated by Django 5.2.13 on 2026-08-09 02:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _fix_zero_datetimes(apps, schema_editor):
    """MySQL rejects ALTER TABLE when legacy rows store 0000-00-00 datetimes."""
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SET SESSION sql_mode = ''")
        cursor.execute(
            """
            UPDATE dispatch_milkdistribution
            SET
              created_at = CASE
                WHEN CAST(created_at AS CHAR) LIKE '0000%%'
                  THEN COALESCE(
                    CASE WHEN CAST(date AS CHAR) LIKE '0000%%' THEN NULL ELSE TIMESTAMP(date) END,
                    UTC_TIMESTAMP()
                  )
                ELSE created_at
              END,
              updated_at = CASE
                WHEN CAST(updated_at AS CHAR) LIKE '0000%%'
                  THEN COALESCE(
                    CASE WHEN CAST(date AS CHAR) LIKE '0000%%' THEN NULL ELSE TIMESTAMP(date) END,
                    UTC_TIMESTAMP()
                  )
                ELSE updated_at
              END,
              date = CASE
                WHEN CAST(date AS CHAR) LIKE '0000%%' THEN CURRENT_DATE()
                ELSE date
              END
            WHERE CAST(created_at AS CHAR) LIKE '0000%%'
               OR CAST(updated_at AS CHAR) LIKE '0000%%'
               OR CAST(date AS CHAR) LIKE '0000%%'
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0015_alter_dispatchnotification_kind'),
        ('masters', '0026_buyer_rates_and_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_fix_zero_datetimes, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='milkdistribution',
            options={'ordering': ['-date', '-id'], 'permissions': [('respond_branch_dispatch', 'Can respond to incoming branch dispatches')]},
        ),
        migrations.AddField(
            model_name='milkdistribution',
            name='billable_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity used for billing (liters or kg per rate_unit).', max_digits=12),
        ),
        migrations.AddField(
            model_name='milkdistribution',
            name='is_billed',
            field=models.BooleanField(default=False, help_text='True after the receivable was posted to the buyer account.'),
        ),
        migrations.AddField(
            model_name='milkdistribution',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='milkdistribution',
            name='rate_unit',
            field=models.CharField(blank=True, choices=[('liter', 'Per liter'), ('kg', 'Per kg')], default='', help_text='liter or kg — empty for branch dispatches.', max_length=10),
        ),
        migrations.AddField(
            model_name='milkdistribution',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='milkdistribution',
            name='unit_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Buyer rate applied when this dispatch was billed.', max_digits=10),
        ),
        migrations.CreateModel(
            name='BuyerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='masters.buyer')),
            ],
            options={
                'ordering': ['buyer__name'],
            },
        ),
        migrations.CreateModel(
            name='BuyerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('credit', 'CREDIT'), ('debit', 'DEBIT')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='masters.buyer')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BuyerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='masters.buyer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyer_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('ledger_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='dispatch.buyertransaction')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BuyerPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='dispatch.milkdistribution')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='dispatch.buyerpayment')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('payment', 'distribution')},
            },
        ),
    ]
