# Generated by Django 5.2.13 on 2026-04-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_alter_employee_first_name_alter_employee_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('nic', 'NIC'), ('passport', 'Passport'), ('driving_licence', 'Driving Licence'), ('other', 'Other')], max_length=20),
        ),
    ]
