# Generated by Django 5.2.13 on 2026-08-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_employee_termination_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nic',
            field=models.CharField(blank=True, db_index=True, help_text='National Identity Card number used for attendance login.', max_length=20, null=True, unique=True),
        ),
    ]
