# Generated by Django 5.2.13 on 2026-08-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_employee_nic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_password_set',
            field=models.BooleanField(default=False, help_text='True after the employee completes first attendance password setup.'),
        ),
    ]
