# Generated by Django 5.2.13 on 2026-04-23 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMilkStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_kg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dispatched_kg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_kg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='milk_stock', to='branches.branch')),
            ],
            options={
                'ordering': ['branch__code'],
            },
        ),
    ]
