# Generated by Django 5.2.13 on 2026-05-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branchmilkstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='collection_unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('liters', 'Liters')], default='kg', help_text='Default unit for entering milk quantity in Milk collection.', max_length=10),
        ),
    ]
