# Generated by Django 5.2.13 on 2026-05-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branchmilkstock_opening_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='collection_unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('liters', 'Liters')], default='kg', help_text='Default unit for entering milk quantity in Milk collection.', max_length=10, verbose_name='Collection unit'),
        ),
    ]
