from django.urls import path

from .views import (
    ConfirmGRNAPI,
    ConsumptionSettlementAPI,
    ConsumptionSettlementCreateView,
    FarmerGoodsCheckAPI,
    FarmerGoodsCheckView,
    FarmerGoodsProductSearchAPI,
    FarmerGoodsIssueAPI,
    FarmerGoodsIssueBatchSettleView,
    FarmerGoodsIssueDeleteView,
    FarmerGoodsIssueHeaderUpdateView,
    FarmerGoodsIssueLineAddView,
    FarmerGoodsIssueLineDeleteView,
    FarmerGoodsIssueLineEditView,
    FarmerGoodsIssueListView,
    FarmerGoodsIssuePrintView,
    FarmerGoodsIssueUpdateView,
    FarmerGoodsIssueView,
    FarmerGoodsStaffAcceptView,
    FarmerGoodsStaffBulkAcceptView,
    FarmerGoodsStaffNotificationFeedView,
    FarmerGoodsStaffRejectView,
    FarmerGoodsPendingAcceptListView,
    FarmerGoodsSettingsView,
    FarmerGoodsDriverRequestDetailJsonView,
    FarmerGoodsDriverRequestFulfillView,
    FarmerGoodsDriverRequestListView,
    FarmerGoodsDriverRequestRejectView,
    GRNAuditModalAPI,
    GRNConfirmView,
    GRNCreateAPI,
    GRNCreateView,
    GRNDeleteView,
    GRNDetailModalAPI,
    GRNListView,
    GRNPrintView,
    GRNStatusUpdateView,
    GRNUpdateView,
    InventoryUsageCreateView,
    RawMilkSupplierCollectionCreateView,
    RawMilkSupplierCollectionDeleteView,
    RawMilkSupplierCollectionInlineQuantityView,
    RawMilkSupplierCollectionListView,
    RawMilkSupplierCollectionPaymentUpdateView,
    RawMilkSupplierCollectionResultUpdateView,
    RawMilkSupplierCollectionStatusUpdateView,
    RawMilkSupplierCollectionUpdateView,
    RawMilkSupplierAccountView,
    RawMilkSupplierDetailView,
    RawMilkSupplierPaymentReceiveView,
    RawMilkSupplierRateCellSaveView,
    RawMilkSupplierRateUpdateView,
    SupplierRateHistoryDeleteView,
    SupplierCreateAPI,
    SupplierQuickCreateView,
    SupplierQuickUpdateView,
    SupplierCreateView,
    SupplierDeleteView,
    SupplierLedgerAPI,
    SupplierLedgerView,
    SupplierListView,
    SupplierPaymentAPI,
    SupplierPaymentCreateView,
    SupplierUpdateView,
)

urlpatterns = [
    path("", SupplierListView.as_view(), name="supplier-list"),
    path("quick-add/", SupplierQuickCreateView.as_view(), name="supplier-quick-add"),
    path("<int:pk>/quick-edit/", SupplierQuickUpdateView.as_view(), name="supplier-quick-edit"),
    path("add/", SupplierCreateView.as_view(), name="supplier-add"),
    path("<int:pk>/edit/", SupplierUpdateView.as_view(), name="supplier-edit"),
    path("<int:pk>/delete/", SupplierDeleteView.as_view(), name="supplier-delete"),
    path("ledger/", SupplierLedgerView.as_view(), name="supplier-ledger"),
    path(
        "raw-milk/suppliers/<int:pk>/",
        RawMilkSupplierDetailView.as_view(),
        name="raw-milk-supplier-detail",
    ),
    path(
        "raw-milk/suppliers/<int:pk>/rate/",
        RawMilkSupplierRateUpdateView.as_view(),
        name="raw-milk-supplier-rate-update",
    ),
    path(
        "raw-milk/suppliers/rate/cell/",
        RawMilkSupplierRateCellSaveView.as_view(),
        name="raw-milk-supplier-rate-cell-save",
    ),
    path(
        "raw-milk/suppliers/<int:supplier_pk>/rate-history/<int:rate_pk>/delete/",
        SupplierRateHistoryDeleteView.as_view(),
        name="raw-milk-supplier-rate-history-delete",
    ),
    path(
        "raw-milk/suppliers/<int:pk>/account/",
        RawMilkSupplierAccountView.as_view(),
        name="raw-milk-supplier-account",
    ),
    path(
        "raw-milk/suppliers/<int:pk>/payments/receive/",
        RawMilkSupplierPaymentReceiveView.as_view(),
        name="raw-milk-supplier-payment-receive",
    ),
    path("raw-milk/collections/", RawMilkSupplierCollectionListView.as_view(), name="raw-milk-collection-list"),
    path("raw-milk/collections/add/", RawMilkSupplierCollectionCreateView.as_view(), name="raw-milk-collection-add"),
    path(
        "raw-milk/collections/<int:pk>/edit/",
        RawMilkSupplierCollectionUpdateView.as_view(),
        name="raw-milk-collection-edit",
    ),
    path(
        "raw-milk/collections/<int:pk>/result/",
        RawMilkSupplierCollectionResultUpdateView.as_view(),
        name="raw-milk-collection-result",
    ),
    path(
        "raw-milk/collections/<int:pk>/status/",
        RawMilkSupplierCollectionStatusUpdateView.as_view(),
        name="raw-milk-collection-status",
    ),
    path(
        "raw-milk/collections/<int:pk>/payment/",
        RawMilkSupplierCollectionPaymentUpdateView.as_view(),
        name="raw-milk-collection-payment",
    ),
    path(
        "raw-milk/collections/<int:pk>/delete/",
        RawMilkSupplierCollectionDeleteView.as_view(),
        name="raw-milk-collection-delete",
    ),
    path(
        "raw-milk/collections/<int:pk>/inline-qty/",
        RawMilkSupplierCollectionInlineQuantityView.as_view(),
        name="raw-milk-collection-inline-qty",
    ),
    path("payments/add/", SupplierPaymentCreateView.as_view(), name="supplier-payment-add"),
    path("grn/", GRNListView.as_view(), name="grn-list"),
    path("grn/add/", GRNCreateView.as_view(), name="grn-add"),
    path("grn/<int:pk>/edit/", GRNUpdateView.as_view(), name="grn-edit"),
    path("grn/<int:pk>/print/", GRNPrintView.as_view(), name="grn-print"),
    path("grn/<int:pk>/view-modal/", GRNDetailModalAPI.as_view(), name="grn-view-modal"),
    path("grn/<int:pk>/audit-modal/", GRNAuditModalAPI.as_view(), name="grn-audit-modal"),
    path("grn/<int:pk>/confirm/", GRNConfirmView.as_view(), name="grn-confirm"),
    path("grn/<int:pk>/status/", GRNStatusUpdateView.as_view(), name="grn-status"),
    path("grn/<int:pk>/delete/", GRNDeleteView.as_view(), name="grn-delete"),
    path("farmer-goods/notifications/feed/", FarmerGoodsStaffNotificationFeedView.as_view(), name="farmer-goods-staff-notification-feed"),
    path("farmer-goods/settings/", FarmerGoodsSettingsView.as_view(), name="farmer-goods-settings"),
    path("farmer-goods/pending-accept/", FarmerGoodsPendingAcceptListView.as_view(), name="farmer-goods-pending-accept-list"),
    path("farmer-goods/pending-accept/bulk-accept/", FarmerGoodsStaffBulkAcceptView.as_view(), name="farmer-goods-staff-bulk-accept"),
    path("farmer-goods/issue/<str:batch_ref>/staff-accept/", FarmerGoodsStaffAcceptView.as_view(), name="farmer-goods-staff-accept"),
    path("farmer-goods/issue/<str:batch_ref>/staff-reject/", FarmerGoodsStaffRejectView.as_view(), name="farmer-goods-staff-reject"),
    path("farmer-goods/driver-requests/", FarmerGoodsDriverRequestListView.as_view(), name="farmer-goods-driver-request-list"),
    path(
        "farmer-goods/driver-requests/<int:pk>/json/",
        FarmerGoodsDriverRequestDetailJsonView.as_view(),
        name="farmer-goods-driver-request-detail-json",
    ),
    path("farmer-goods/driver-requests/<int:pk>/", FarmerGoodsDriverRequestFulfillView.as_view(), name="farmer-goods-driver-request-fulfill"),
    path(
        "farmer-goods/driver-requests/<int:pk>/reject/",
        FarmerGoodsDriverRequestRejectView.as_view(),
        name="farmer-goods-driver-request-reject",
    ),
    path("farmer-goods/check/", FarmerGoodsCheckView.as_view(), name="farmer-goods-check"),
    path("farmer-goods/issues/", FarmerGoodsIssueListView.as_view(), name="farmer-goods-issue-list"),
    path("farmer-goods/issue/<str:batch_ref>/settle/", FarmerGoodsIssueBatchSettleView.as_view(), name="farmer-goods-issue-settle"),
    path("farmer-goods/issue/<str:batch_ref>/delete/", FarmerGoodsIssueDeleteView.as_view(), name="farmer-goods-issue-delete"),
    path("farmer-goods/issue/<str:batch_ref>/edit/", FarmerGoodsIssueUpdateView.as_view(), name="farmer-goods-issue-edit"),
    path(
        "farmer-goods/issue/<str:batch_ref>/header/",
        FarmerGoodsIssueHeaderUpdateView.as_view(),
        name="farmer-goods-issue-header",
    ),
    path(
        "farmer-goods/issue/<str:batch_ref>/add-line/",
        FarmerGoodsIssueLineAddView.as_view(),
        name="farmer-goods-issue-line-add",
    ),
    path("farmer-goods/issue/<str:batch_ref>/print/", FarmerGoodsIssuePrintView.as_view(), name="farmer-goods-issue-print"),
    path(
        "farmer-goods/issue-line/<int:issue_id>/edit/",
        FarmerGoodsIssueLineEditView.as_view(),
        name="farmer-goods-issue-line-edit",
    ),
    path(
        "farmer-goods/issue-line/<int:issue_id>/delete/",
        FarmerGoodsIssueLineDeleteView.as_view(),
        name="farmer-goods-issue-line-delete",
    ),
    path("farmer-goods/issue/", FarmerGoodsIssueView.as_view(), name="farmer-goods-issue"),
    path("farmer-goods/consume/", ConsumptionSettlementCreateView.as_view(), name="farmer-goods-consume"),
    path("inventory/usage/", InventoryUsageCreateView.as_view(), name="inventory-usage-add"),
    path("api/suppliers/", SupplierCreateAPI.as_view(), name="api-supplier-create"),
    path("api/grn/", GRNCreateAPI.as_view(), name="api-grn-create"),
    path("api/grn/confirm/", ConfirmGRNAPI.as_view(), name="api-grn-confirm"),
    path("api/farmer-goods/products/", FarmerGoodsProductSearchAPI.as_view(), name="api-farmer-goods-products"),
    path("api/farmer-goods/check/", FarmerGoodsCheckAPI.as_view(), name="api-farmer-goods-check"),
    path("api/farmer-goods/issue/", FarmerGoodsIssueAPI.as_view(), name="api-farmer-goods-issue"),
    path("api/farmer-goods/consume/", ConsumptionSettlementAPI.as_view(), name="api-farmer-goods-consume"),
    path("api/payments/", SupplierPaymentAPI.as_view(), name="api-supplier-payment"),
    path("api/ledger/", SupplierLedgerAPI.as_view(), name="api-supplier-ledger"),
]
