# Generated by Django 5.2.13 on 2026-06-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_farmerpaymentloandeductionsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmerpaymentloandeductionsetting',
            options={'ordering': ['-period_end', '-period_start', 'farmer_id'], 'permissions': [('view_farmerpaymentsheet', 'Can view farmer payment sheet')]},
        ),
    ]
