# Generated by Django 5.2.13 on 2026-06-24 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_collectionpoint_collector_fee'),
        ('reports', '0005_collectionpointpaymentsheet_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPointPeriodPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_amount', models.DecimalField(decimal_places=2, help_text='Payable amount at the time of recording.', max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('branch_ids', models.JSONField(blank=True, default=list)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('collection_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_payments', to='masters.collectionpoint')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_point_period_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('collection_point', 'period_start', 'period_end'), name='uniq_collection_point_period_payment')],
            },
        ),
        migrations.CreateModel(
            name='FarmerPeriodPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_amount', models.DecimalField(decimal_places=2, help_text='Net payable at the time of recording.', max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('branch_ids', models.JSONField(blank=True, default=list)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_payments', to='masters.farmer')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farmer_period_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('farmer', 'period_start', 'period_end'), name='uniq_farmer_period_payment')],
            },
        ),
    ]
