# Generated by Django 5.2.13 on 2026-06-25 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0016_payment_settlement_flags"),
        ("reports", "0009_grant_financial_view_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerPaymentPeriodDeductionSkip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("advance", "Advance"),
                            ("goods_line", "Goods line"),
                            ("goods_receipt", "Goods receipt"),
                            ("loan_instalment", "Loan instalment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference_id", models.PositiveBigIntegerField(default=0)),
                ("reference_key", models.CharField(blank=True, default="", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_deduction_skips",
                        to="masters.farmer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="farmer_payment_deduction_skips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="farmerpaymentperioddeductionskip",
            constraint=models.UniqueConstraint(
                fields=(
                    "farmer",
                    "period_start",
                    "period_end",
                    "kind",
                    "reference_id",
                    "reference_key",
                ),
                name="uniq_farmer_payment_period_deduction_skip",
            ),
        ),
    ]
