# Generated by Django 5.2.13 on 2026-06-26 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grant_collection_point_deduction_skip_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("auth", "User")

    try:
        farmer_skip_perm = Permission.objects.get(
            codename="change_farmerpaymentperioddeductionskip",
            content_type__app_label="reports",
        )
        cp_skip_perm = Permission.objects.get(
            codename="change_collectionpointpaymentperioddeductionskip",
            content_type__app_label="reports",
        )
    except Permission.DoesNotExist:
        return

    for group in Group.objects.filter(permissions=farmer_skip_perm):
        group.permissions.add(cp_skip_perm)
    for user in User.objects.filter(user_permissions=farmer_skip_perm):
        user.user_permissions.add(cp_skip_perm)


def revoke_collection_point_deduction_skip_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("auth", "User")

    try:
        cp_skip_perm = Permission.objects.get(
            codename="change_collectionpointpaymentperioddeductionskip",
            content_type__app_label="reports",
        )
    except Permission.DoesNotExist:
        return

    for group in Group.objects.filter(permissions=cp_skip_perm):
        group.permissions.remove(cp_skip_perm)
    for user in User.objects.filter(user_permissions=cp_skip_perm):
        user.user_permissions.remove(cp_skip_perm)


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0016_payment_settlement_flags"),
        ("reports", "0012_manual_settlement_permission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionPointPaymentPeriodDeductionSkip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("goods_line", "Goods line"),
                            ("goods_receipt", "Goods receipt"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference_id", models.PositiveBigIntegerField(default=0)),
                ("reference_key", models.CharField(blank=True, default="", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_deduction_skips",
                        to="masters.collectionpoint",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collection_point_payment_deduction_skips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="collectionpointpaymentperioddeductionskip",
            constraint=models.UniqueConstraint(
                fields=(
                    "collection_point",
                    "period_start",
                    "period_end",
                    "kind",
                    "reference_id",
                    "reference_key",
                ),
                name="uniq_collection_point_payment_period_deduction_skip",
            ),
        ),
        migrations.RunPython(
            grant_collection_point_deduction_skip_permissions,
            revoke_collection_point_deduction_skip_permissions,
        ),
    ]
