# Generated by Django 5.2.13 on 2026-07-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_collectionpointperiodpayment_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpointpaymentperioddeductionskip',
            name='kind',
            field=models.CharField(choices=[('advance', 'Advance'), ('goods_line', 'Goods line'), ('goods_receipt', 'Goods receipt'), ('loan_instalment', 'Loan instalment')], max_length=20),
        ),
    ]
