# Generated by Django 5.2.13 on 2026-08-17 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0029_advance_previous_outstanding"),
        ("reports", "0019_collectionpoint_deduction_skip_advance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionpointperiodpayment",
            name="previous_outstanding_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Previous outstanding deducted when this payment was recorded.",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CollectionPointPreviousOutstanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("originated_period_start", models.DateField()),
                ("originated_period_end", models.DateField()),
                (
                    "available_on",
                    models.DateField(
                        help_text="First date this outstanding can be deducted on a payment sheet.",
                    ),
                ),
                ("is_recovered", models.BooleanField(default=False)),
                ("recovered_at", models.DateTimeField(blank=True, null=True)),
                ("recovered_period_start", models.DateField(blank=True, null=True)),
                ("recovered_period_end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_outstanding_records",
                        to="masters.collectionpoint",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collection_point_previous_outstanding_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "originated_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="originated_previous_outstanding",
                        to="reports.collectionpointperiodpayment",
                    ),
                ),
            ],
            options={
                "verbose_name": "collection point previous outstanding",
                "verbose_name_plural": "collection point previous outstanding",
                "ordering": ["-available_on", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="collectionpointpreviousoutstanding",
            index=models.Index(
                fields=["collection_point", "is_recovered", "available_on"],
                name="cp_prev_os_open_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionpointpreviousoutstanding",
            constraint=models.UniqueConstraint(
                fields=[
                    "collection_point",
                    "originated_period_start",
                    "originated_period_end",
                ],
                name="uniq_cp_previous_outstanding_period",
            ),
        ),
    ]
