# Generated by Django 5.2.13 on 2026-08-18 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0031_collectionpointadvance_partial_recovery'),
        ('reports', '0022_collectionpoint_payment_loan_deduction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpointperiodpayment',
            name='payment_correction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual payment correction applied when this payment was recorded.', max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='CollectionPointPaymentCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_corrections', to='masters.collectionpoint')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_point_payment_corrections_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', '-period_start', 'collection_point_id'],
                'constraints': [models.UniqueConstraint(fields=('collection_point', 'period_start', 'period_end'), name='uniq_cp_payment_correction_period')],
            },
        ),
    ]
