# Generated by Django 5.2.13 on 2026-08-19 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0032_collection_point_bank_accounts'),
        ('reports', '0023_collection_point_payment_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpointperiodpayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_payments', to='masters.collectionpointbankaccount'),
        ),
        migrations.AddField(
            model_name='collectionpointperiodpayment',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='collectionpointperiodpayment',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='collectionpointperiodpayment',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='collectionpointperiodpayment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='collectionpointperiodpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer')], default='cash', max_length=20),
        ),
    ]
