from django.urls import path
from .views import (
    MilkDistributionListView,
    MilkDistributionCreateView,
    MilkDistributionUpdateView,
    MilkDistributionBuyerResultUpdateView,
    MilkDistributionPaymentUpdateView,
    MilkDistributionBulkPaymentUpdateView,
    MilkDistributionBillingRateUpdateView,
    MilkDistributionBulkBillingRateUpdateView,
    MilkDistributionStatusUpdateView,
    MilkDistributionDeleteView,
    MilkDistributionInlineQuantityView,
    MilkDistributionBranchRespondView,
    MilkDistributionBranchReturnResolveView,
    DispatchNotificationMarkReadView,
    DispatchNotificationMarkAllReadView,
    DispatchNotificationFeedView,
    BuyerRateForDateView,
)

urlpatterns = [
    path('', MilkDistributionListView.as_view(), name='distribution-list'),
    path('add/', MilkDistributionCreateView.as_view(), name='distribution-add'),
    path('<int:pk>/buyer-result/', MilkDistributionBuyerResultUpdateView.as_view(), name='distribution-buyer-result'),
    path('<int:pk>/branch-respond/', MilkDistributionBranchRespondView.as_view(), name='distribution-branch-respond'),
    path('<int:pk>/branch-return/', MilkDistributionBranchReturnResolveView.as_view(), name='distribution-branch-return'),
    path('<int:pk>/status/', MilkDistributionStatusUpdateView.as_view(), name='distribution-status'),
    path('<int:pk>/payment/', MilkDistributionPaymentUpdateView.as_view(), name='distribution-payment'),
    path('bulk-payment/', MilkDistributionBulkPaymentUpdateView.as_view(), name='distribution-bulk-payment'),
    path('<int:pk>/billing-rate/', MilkDistributionBillingRateUpdateView.as_view(), name='distribution-rate'),
    path('bulk-billing-rate/', MilkDistributionBulkBillingRateUpdateView.as_view(), name='distribution-bulk-rate'),
    path('<int:pk>/edit/', MilkDistributionUpdateView.as_view(), name='distribution-edit'),
    path('<int:pk>/delete/', MilkDistributionDeleteView.as_view(), name='distribution-delete'),
    path('<int:pk>/inline-qty/', MilkDistributionInlineQuantityView.as_view(), name='distribution-inline-qty'),
    path('buyer-rate/', BuyerRateForDateView.as_view(), name='dispatch-buyer-rate'),
    path('notifications/feed/', DispatchNotificationFeedView.as_view(), name='dispatch-notification-feed'),
    path('notifications/<int:pk>/read/', DispatchNotificationMarkReadView.as_view(), name='dispatch-notification-read'),
    path('notifications/read-all/', DispatchNotificationMarkAllReadView.as_view(), name='dispatch-notification-read-all'),
]
