# Generated by Django 5.2.13 on 2026-04-30 03:00

from django.db import migrations, models


def seed_product_categories(apps, schema_editor):
    ProductCategory = apps.get_model("stock_management", "ProductCategory")
    defaults = [
        ("cattle_feeds", "Cattle Feeds"),
        ("minerals", "Minerals"),
        ("vitamins", "Vitamins"),
        ("ropes", "Ropes"),
    ]
    for code, name in defaults:
        ProductCategory.objects.get_or_create(code=code, defaults={"name": name})


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Product categories',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_product_categories, migrations.RunPython.noop),
    ]
