# Generated by Django 5.2.13 on 2026-05-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0003_stock_transfer_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklog',
            name='action_type',
            field=models.CharField(choices=[('grn', 'GRN'), ('transfer', 'TRANSFER'), ('issue', 'ISSUE')], max_length=20),
        ),
    ]
