# Generated by Django 5.2.13 on 2026-05-04 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0004_add_grn_stocklog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfernote',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
