# Generated by Django 5.2.13 on 2026-08-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0007_stocktransferline_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklog',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
