# Generated by Django 5.2.13 on 2026-08-11 07:19

from decimal import Decimal

from django.db import migrations, models


def clamp_negative_stock(apps, schema_editor):
    BranchStock = apps.get_model("stock_management", "BranchStock")
    MainStock = apps.get_model("stock_management", "MainStock")
    BranchStock.objects.filter(quantity__lt=0).update(quantity=Decimal("0.00"))
    MainStock.objects.filter(quantity__lt=0).update(quantity=Decimal("0.00"))


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0007_branch_details"),
        ("stock_management", "0008_stocklog_reference"),
    ]

    operations = [
        migrations.RunPython(clamp_negative_stock, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="branchstock",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="branchstock_quantity_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="mainstock",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="mainstock_quantity_gte_0",
            ),
        ),
    ]
