# Generated by Django 5.2.13 on 2026-08-11 07:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_branch_details'),
        ('stock_management', '0009_stock_quantity_non_negative'),
        ('suppliers', '0020_stock_quantity_non_negative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockissue',
            name='issued_to_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('collection_point', 'Collection Point'), ('stocktake', 'Stocktake write-off')], max_length=20),
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_number', models.CharField(blank=True, max_length=32, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=12)),
                ('remarks', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='branches.branch')),
                ('correction_grn', models.ForeignKey(blank=True, help_text='STOCK_CORRECTION GRN created for excess lines when posted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to='suppliers.grn')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'permissions': [('post_stockcount', 'Can post stock count')],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='System Available at snapshot / last refresh.', max_digits=14)),
                ('physical_qty', models.DecimalField(blank=True, decimal_places=2, help_text='Physical counted quantity. Blank until counted.', max_digits=14, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock_management.stockcount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_lines', to='stock_management.product')),
            ],
            options={
                'ordering': ['product__name', 'id'],
                'unique_together': {('count', 'product')},
            },
        ),
    ]
