# Generated by Django 5.2.13 on 2026-07-02 16:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0007_branch_details'),
        ('masters', '0020_farmer_status_resignation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPointLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_reference', models.CharField(blank=True, max_length=60)),
                ('average_monthly_milk_production', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('average_monthly_milk_income', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('loan_date', models.DateField(default=django.utils.timezone.localdate)),
                ('first_repayment_date', models.DateField()),
                ('installment_count', models.PositiveIntegerField(help_text='Total number of instalments (2 per month: 15th and month-end).')),
                ('requested_installment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='When set, each instalment uses this amount except the last (remainder).', max_digits=14, null=True)),
                ('is_existing_loan', models.BooleanField(default=False, help_text='Loan already in progress before it was recorded in the system.')),
                ('prior_paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount already paid on this loan before system entry.', max_digits=14)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_collection_point_loans', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_point_loans', to='branches.branch')),
                ('collection_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='masters.collectionpoint')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_collection_point_loans', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_collection_point_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cp_loan',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CollectionPointLoanActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_label', models.CharField(blank=True, max_length=40)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('submitted', 'Submitted for approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reverted_to_draft', 'Reverted to draft'), ('schedule_paid_updated', 'Repayment schedule paid amounts updated')], max_length=30)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='collection_point_loans.collectionpointloan')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_point_loan_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cp_loan_action_log',
                'ordering': ['-performed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CollectionPointLoanRepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('payment_note', models.CharField(blank=True, max_length=255)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedules', to='collection_point_loans.collectionpointloan')),
            ],
            options={
                'db_table': 'cp_loan_schedule',
                'ordering': ['installment_number'],
                'constraints': [models.UniqueConstraint(fields=('loan', 'installment_number'), name='cp_loan_sched_loan_inst_uniq')],
            },
        ),
    ]
