# Generated by Django 5.2.13 on 2026-08-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_point_loans', '0004_schedule_available_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpointloanrepaymentschedule',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('direct', 'Direct'), ('milk_payment_sheet', 'Payment sheet settlement')], max_length=20),
        ),
    ]
