# Generated by Django 5.2.13 on 2026-08-18 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_point_loans', '0005_instalment_payment_method'),
        ('reports', '0023_collection_point_payment_correction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPointLoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('method', models.CharField(choices=[('direct', 'Direct'), ('milk_payment_sheet', 'Payment sheet settlement')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_point_loan_payments_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='collection_point_loans.collectionpointloan')),
                ('source_period_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payment_transactions', to='reports.collectionpointperiodpayment')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CollectionPointLoanPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='collection_point_loans.collectionpointloanpayment')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='collection_point_loans.collectionpointloanrepaymentschedule')),
            ],
            options={
                'ordering': ['payment_id', 'schedule__installment_number', 'id'],
            },
        ),
    ]
