# Generated by Django 5.2.13 on 2026-08-11 09:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm', '0006_employee_nic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_type', models.CharField(choices=[('check_in', 'Check in'), ('check_out', 'Check out')], max_length=20)),
                ('punched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_label', models.CharField(blank=True, max_length=255)),
                ('app_label', models.CharField(blank=True, default='Web', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='hrm.employee')),
            ],
            options={
                'ordering': ['-punched_at', '-id'],
                'permissions': [('view_attendance_admin', 'Can view full attendance details (admin)')],
                'indexes': [models.Index(fields=['employee', '-punched_at'], name='attendance__employe_76c1d6_idx'), models.Index(fields=['punch_type', '-punched_at'], name='attendance__punch_t_983ad5_idx')],
            },
        ),
    ]
